
package sicore.medidores.servicios.ifc.medidores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import bpe.common.servicios.peticiones.Peticion;
import bpe.common.servicios.respuestas.Respuesta;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Medidores", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/")
@XmlSeeAlso({
    bpe.common.servicios.peticiones.ObjectFactory.class,
    bpe.common.servicios.respuestas.ObjectFactory.class,
    bpe.cuentas.servicios.entidades.ObjectFactory.class,
    sicore.cortes.servicios.ifc.cortes.ObjectFactory.class,
    sicore.medidores.servicios.ifc.medidores.ObjectFactory.class
})
public interface Medidores {


    /**
     * 
     * @param peticion
     * @return
     *     returns sicore.medidores.servicios.ifc.medidores.LecturaRespuesta
     */
    @WebMethod(operationName = "InsertarLectura", action = "http://medidores.ifc.servicios.medidores.sicore/Medidores/InsertarLecturaRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "InsertarLectura", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.InsertarLectura")
    @ResponseWrapper(localName = "InsertarLecturaResponse", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.InsertarLecturaResponse")
    public LecturaRespuesta insertarLectura(
        @WebParam(name = "peticion", targetNamespace = "")
        LecturaPeticion peticion);

    /**
     * 
     * @param peticion
     * @return
     *     returns sicore.medidores.servicios.ifc.medidores.LecturaArchivosPlanosRespuesta
     */
    @WebMethod(operationName = "LecturaArhivosPlanos", action = "http://medidores.ifc.servicios.medidores.sicore/Medidores/LecturaArhivosPlanosRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "LecturaArhivosPlanos", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.LecturaArhivosPlanos")
    @ResponseWrapper(localName = "LecturaArhivosPlanosResponse", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.LecturaArhivosPlanosResponse")
    public LecturaArchivosPlanosRespuesta lecturaArhivosPlanos(
        @WebParam(name = "peticion", targetNamespace = "")
        LecturaArchivosPlanosPeticion peticion);

    /**
     * 
     * @param peticion
     * @return
     *     returns sicore.medidores.servicios.ifc.medidores.RutasEstadoRespuesta
     */
    @WebMethod(operationName = "ConsultarRutasEstado", action = "http://medidores.ifc.servicios.medidores.sicore/Medidores/ConsultarRutasEstadoRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConsultarRutasEstado", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.ConsultarRutasEstado")
    @ResponseWrapper(localName = "ConsultarRutasEstadoResponse", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.ConsultarRutasEstadoResponse")
    public RutasEstadoRespuesta consultarRutasEstado(
        @WebParam(name = "peticion", targetNamespace = "")
        ConsultarRutasEstadoPeticion peticion);

    /**
     * 
     * @param peticion
     * @return
     *     returns sicore.medidores.servicios.ifc.medidores.RutasEstadoRespuesta
     */
    @WebMethod(operationName = "ActualizarRutasEstado", action = "http://medidores.ifc.servicios.medidores.sicore/Medidores/ActualizarRutasEstadoRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ActualizarRutasEstado", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.ActualizarRutasEstado")
    @ResponseWrapper(localName = "ActualizarRutasEstadoResponse", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.ActualizarRutasEstadoResponse")
    public RutasEstadoRespuesta actualizarRutasEstado(
        @WebParam(name = "peticion", targetNamespace = "")
        RutasEstadoPeticion peticion);

    /**
     * 
     * @param peticion
     * @return
     *     returns bpe.common.servicios.respuestas.Respuesta
     */
    @WebMethod(operationName = "GenerarRecepcionPalm", action = "http://medidores.ifc.servicios.medidores.sicore/Medidores/GenerarRecepcionPalmRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GenerarRecepcionPalm", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.GenerarRecepcionPalm")
    @ResponseWrapper(localName = "GenerarRecepcionPalmResponse", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.GenerarRecepcionPalmResponse")
    public Respuesta generarRecepcionPalm(
        @WebParam(name = "peticion", targetNamespace = "")
        GenerarRecepcionPalmPeticion peticion);

    /**
     * 
     * @param peticion
     * @return
     *     returns sicore.medidores.servicios.ifc.medidores.RecepcionPalmRespuesta
     */
    @WebMethod(operationName = "Bitacora", action = "http://medidores.ifc.servicios.medidores.sicore/Medidores/BitacoraRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Bitacora", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.Bitacora")
    @ResponseWrapper(localName = "BitacoraResponse", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.BitacoraResponse")
    public RecepcionPalmRespuesta bitacora(
        @WebParam(name = "peticion", targetNamespace = "")
        BitacoraPeticion peticion);

    /**
     * 
     * @param peticion
     * @return
     *     returns sicore.medidores.servicios.ifc.medidores.CantidadBitacoraRespuesta
     */
    @WebMethod(operationName = "CantidadBitacora", action = "http://medidores.ifc.servicios.medidores.sicore/Medidores/CantidadBitacoraRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CantidadBitacora", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.CantidadBitacora")
    @ResponseWrapper(localName = "CantidadBitacoraResponse", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.CantidadBitacoraResponse")
    public CantidadBitacoraRespuesta cantidadBitacora(
        @WebParam(name = "peticion", targetNamespace = "")
        BitacoraPeticion peticion);

    /**
     * 
     * @param peticion
     * @return
     *     returns bpe.common.servicios.peticiones.Peticion
     */
    @WebMethod(operationName = "ActualizarDescargaBitacora", action = "http://medidores.ifc.servicios.medidores.sicore/Medidores/ActualizarDescargaBitacoraRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ActualizarDescargaBitacora", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.ActualizarDescargaBitacora")
    @ResponseWrapper(localName = "ActualizarDescargaBitacoraResponse", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.ActualizarDescargaBitacoraResponse")
    public Peticion actualizarDescargaBitacora(
        @WebParam(name = "peticion", targetNamespace = "")
        ActualizarDescargaPeticion peticion);

    /**
     * 
     * @param peticion
     * @return
     *     returns sicore.medidores.servicios.ifc.medidores.RecepcionPalmRespuesta
     */
    @WebMethod(operationName = "ActualizarRecepcionPalm", action = "http://medidores.ifc.servicios.medidores.sicore/Medidores/ActualizarRecepcionPalmRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ActualizarRecepcionPalm", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.ActualizarRecepcionPalm")
    @ResponseWrapper(localName = "ActualizarRecepcionPalmResponse", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.ActualizarRecepcionPalmResponse")
    public RecepcionPalmRespuesta actualizarRecepcionPalm(
        @WebParam(name = "peticion", targetNamespace = "")
        RecepcionPalmPeticion peticion);

    /**
     * 
     * @param peticion
     * @return
     *     returns sicore.medidores.servicios.ifc.medidores.RecepcionPalmRespuesta
     */
    @WebMethod(operationName = "ConsultarRecepcionPalm", action = "http://medidores.ifc.servicios.medidores.sicore/Medidores/ConsultarRecepcionPalmRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConsultarRecepcionPalm", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.ConsultarRecepcionPalm")
    @ResponseWrapper(localName = "ConsultarRecepcionPalmResponse", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.ConsultarRecepcionPalmResponse")
    public RecepcionPalmRespuesta consultarRecepcionPalm(
        @WebParam(name = "peticion", targetNamespace = "")
        BitacoraPeticion peticion);

    /**
     * 
     * @param peticion
     * @return
     *     returns sicore.medidores.servicios.ifc.medidores.NovedadRespuesta
     */
    @WebMethod(operationName = "ConsultarNovedades", action = "http://medidores.ifc.servicios.medidores.sicore/Medidores/ConsultarNovedadesRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConsultarNovedades", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.ConsultarNovedades")
    @ResponseWrapper(localName = "ConsultarNovedadesResponse", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.ConsultarNovedadesResponse")
    public NovedadRespuesta consultarNovedades(
        @WebParam(name = "peticion", targetNamespace = "")
        NovedadPeticion peticion);

    /**
     * 
     * @param peticion
     * @return
     *     returns bpe.common.servicios.respuestas.Respuesta
     */
    @WebMethod(operationName = "InsertarRecepcionSobrantes", action = "http://medidores.ifc.servicios.medidores.sicore/Medidores/InsertarRecepcionSobrantesRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "InsertarRecepcionSobrantes", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.InsertarRecepcionSobrantes")
    @ResponseWrapper(localName = "InsertarRecepcionSobrantesResponse", targetNamespace = "http://medidores.ifc.servicios.medidores.sicore/", className = "sicore.medidores.servicios.ifc.medidores.InsertarRecepcionSobrantesResponse")
    public Respuesta insertarRecepcionSobrantes(
        @WebParam(name = "peticion", targetNamespace = "")
        RecepcionSobrantesPeticion peticion);

}
