package app.microservicio.tweeter.timer;

import app.microservicio.tweeter.timer.BotAutomatico.*;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;

import java.util.Date;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.core.io.ResourceLoader;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import app.microservicio.tweeter.componente.GestorVictima;
import twitter4j.StatusUpdate;
import twitter4j.Twitter;
public class BotAutomaticoTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(BotAutomatico.class, notNullValue());
	}

	@Test
	public void instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		BotAutomatico target = new BotAutomatico();
		assertThat(target, notNullValue());
	}

	@Test
	public void actualizacionEstado_A$() throws Exception {
		// TODO auto-generated by JUnit Helper.
		BotAutomatico target = new BotAutomatico();
		target.actualizacionEstado();
	}

}
