import ChangeCase(elem).*;
import junit.framework.TestCase;

public class ChangeCase(elem)Test extends TestCase {

	public void test_type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertNotNull(ChangeCase(elem).class);
	}

	public void test_instantiation() throws Exception {
		// TODO auto-generated by JUnit Helper.
		ChangeCase(elem) target = new ChangeCase(elem)();
		assertNotNull(target);
	}

	public void test_and_A$Object() throws Exception {
		// TODO auto-generated by JUnit Helper.
		ChangeCase(elem) target = new ChangeCase(elem)();
		Object 575px = null;
		Object actual = target.and(575px);
		Object expected = null;
		assertEquals(expected, actual);
	}

}
