
package sicore.seguridad.servicios.ifc.seguridad;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import bpe.common.servicios.peticiones.Peticion;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Seguridad", targetNamespace = "http://seguridad.ifc.servicios.seguridad.sicore/")
@XmlSeeAlso({
    bpe.common.servicios.peticiones.ObjectFactory.class,
    bpe.common.servicios.respuestas.ObjectFactory.class,
    bpe.cuentas.servicios.entidades.ObjectFactory.class,
    sicore.cortes.servicios.ifc.cortes.ObjectFactory.class,
    sicore.seguridad.servicios.ifc.seguridad.ObjectFactory.class
})
public interface Seguridad {


    /**
     * 
     * @param userPassword
     * @param userUsuario
     * @param peticion
     * @return
     *     returns sicore.seguridad.servicios.ifc.seguridad.ConsultarLoginRespuesta
     */
    @WebMethod(action = "http://seguridad.ifc.servicios.seguridad.sicore/Seguridad/consultaLoginRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaLogin", targetNamespace = "http://seguridad.ifc.servicios.seguridad.sicore/", className = "sicore.seguridad.servicios.ifc.seguridad.ConsultaLogin")
    @ResponseWrapper(localName = "consultaLoginResponse", targetNamespace = "http://seguridad.ifc.servicios.seguridad.sicore/", className = "sicore.seguridad.servicios.ifc.seguridad.ConsultaLoginResponse")
    public ConsultarLoginRespuesta consultaLogin(
        @WebParam(name = "peticion", targetNamespace = "")
        Peticion peticion,
        @WebParam(name = "userUsuario", targetNamespace = "")
        String userUsuario,
        @WebParam(name = "userPassword", targetNamespace = "")
        String userPassword);

    /**
     * 
     * @param userUsuario
     * @param peticion
     * @return
     *     returns sicore.seguridad.servicios.ifc.seguridad.ConsultarOpcionesRespuesta
     */
    @WebMethod(action = "http://seguridad.ifc.servicios.seguridad.sicore/Seguridad/consultarOpcionesRequest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarOpciones", targetNamespace = "http://seguridad.ifc.servicios.seguridad.sicore/", className = "sicore.seguridad.servicios.ifc.seguridad.ConsultarOpciones")
    @ResponseWrapper(localName = "consultarOpcionesResponse", targetNamespace = "http://seguridad.ifc.servicios.seguridad.sicore/", className = "sicore.seguridad.servicios.ifc.seguridad.ConsultarOpcionesResponse")
    public ConsultarOpcionesRespuesta consultarOpciones(
        @WebParam(name = "peticion", targetNamespace = "")
        Peticion peticion,
        @WebParam(name = "userUsuario", targetNamespace = "")
        String userUsuario);

}
